#!/usr/bin/env bash
# ingest-trace-substrate.sh — nightly trace-substrate ingest (mem-75t.4).
#
# Mechanical cron-triggered exec, no LLM. Three steps:
#
#   1. Build the MERGED session<->bead join (events-primary: gc events + dolt
#      history + content scan) and archive every bead-linked transcript to
#      durable storage — the transcript corpus is a ~6-week rolling window, so
#      this step is the one racing data loss.
#   2. Run `mem ingest-traces --session-join <artifact>` from the gas-city
#      checkout (the cwd `--with-traces` needs to resolve residue transcripts
#      via `gc session logs`) into a scratch store.
#   3. Verify the coverage axes came back non-zero, carry the append-only
#      lessons table across (the one table a rebuild cannot regenerate), and
#      only then swap over the live sidecar.
#
# Idempotent: the writer upserts records and rebuilds child rows; the join
# build re-derives from append-only inputs; archival skips unchanged files. A
# run that resolves zero traces (wrong cwd) is detected and aborts the swap.
set -eo pipefail

GC_CITY="${GC_CITY:-/home/ds/gas-city}"
MEM_REPO="${MEM_REPO:-/home/ds/projects/mem}"
STORE="${MEM_STORE:-$MEM_REPO/.mem/store.db}"
MEM_BIN="${MEM_BIN:-$MEM_REPO/bin/mem}"
LOG="${INGEST_LOG:-$MEM_REPO/.mem/ingest-trace-substrate.log}"
JOIN="${MEM_SESSION_JOIN:-$MEM_REPO/.mem/merged-session-bead-join.json}"
TASK_TYPES="${MEM_TASK_TYPES:-$MEM_REPO/.mem/task-types.json}"

SCRATCH_DIR="$(mktemp -d)"
SCRATCH="$SCRATCH_DIR/store.db"
trap 'rm -rf "$SCRATCH_DIR"' EXIT
DATE_UTC=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- 1. merged join + transcript archival (time-sensitive: rolling corpus) ---
cd "$MEM_REPO/memory-bench"
uv run python scripts/build_merged_join.py --store "$STORE" --out "$JOIN"

JOIN_MULTI=$(jq -r '.stats.multi_session_beads' "$JOIN")
ARCHIVED=$(jq -cr '.archive // empty' "$JOIN")

# --- 1b. model task-type classification (incremental: new beads only) --------
# Failure here must not block the ingest — types just stay absent for a night.
uv run python scripts/classify_task_types.py --store "$STORE" --out "$TASK_TYPES" \
  || echo "classify_task_types failed; continuing without fresh model types" >&2

# --- 2. store rebuild with the merged join ------------------------------------
cd "$GC_CITY"

# --json so we can read the coverage report back deterministically instead of
# scraping the human lines.
TT_FLAG=()
[ -f "$TASK_TYPES" ] && TT_FLAG=(--task-types "$TASK_TYPES")
RESULT=$("$MEM_BIN" ingest-traces --store "$SCRATCH" --session-join "$JOIN" "${TT_FLAG[@]}" --json)

# Pull the after-coverage out of the success envelope.
read -r WITH_TRACE TRACE_ERRORS WITH_BASE RECORDS MULTI <<EOF
$(echo "$RESULT" | jq -r '.data.after | "\(.with_trace) \(.trace_errors) \(.with_base_commit) \(.records) \(.multi_session)"')
EOF

DELTA=$(echo "$RESULT" | jq -c '.data.delta')

# Guard: a real full run lifts traces off zero. Zero across the board means the
# transcripts did not resolve (wrong cwd / city) — do NOT swap, the live store
# is better than an empty one. Fail loudly so the cron surfaces it.
if [ "${WITH_TRACE:-0}" -eq 0 ] && [ "${TRACE_ERRORS:-0}" -eq 0 ] && [ "${WITH_BASE:-0}" -eq 0 ]; then
  echo "$DATE_UTC ABORT records=$RECORDS with_trace=0 trace_errors=0 with_base_commit=0 (no traces resolved; store NOT swapped)" >>"$LOG"
  echo "ingest-trace-substrate: no traces resolved — refusing to swap an empty store" >&2
  exit 1
fi

# --- 3. carry lessons across, then swap ---------------------------------------
# The lessons table is append-only and NOT regenerated by a rebuild: export
# from the live store and import into the scratch before it replaces the live.
if [ -f "$STORE" ]; then
  LESSONS="$SCRATCH_DIR/lessons.ndjson"
  "$MEM_BIN" export-lessons --store "$STORE" --out "$LESSONS" >/dev/null
  if [ -s "$LESSONS" ]; then
    "$MEM_BIN" import-lessons --store "$SCRATCH" --file "$LESSONS" >/dev/null
  fi
fi

mkdir -p "$(dirname "$STORE")"
mv "$SCRATCH" "$STORE"
# Stale WAL/SHM from the previous store must not pair with the new file.
rm -f "$STORE-wal" "$STORE-shm"

echo "$DATE_UTC OK records=$RECORDS with_trace=$WITH_TRACE trace_errors=$TRACE_ERRORS with_base_commit=$WITH_BASE multi_session=$MULTI join_multi=$JOIN_MULTI archive=$ARCHIVED delta=$DELTA" >>"$LOG"
echo "ingest-trace-substrate: swapped store records=$RECORDS with_trace=$WITH_TRACE trace_errors=$TRACE_ERRORS with_base_commit=$WITH_BASE multi_session=$MULTI"
